### PR TITLE
Update recipe and feedstock

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

---

Refreshing the recipe and the feedstock. Attempting to address issues identified recently in #31:

* Added `{{ stdlib("c") }}`, bumped build number, and rerendered
* Removed the duplicate key `skip` that was breaking the parsing by conda-souschef ([error](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12261954318/job/34210161600#step:5:124) was `found duplicate key "skip" with value "True" (original value: "True")`). There is no danger of attempting to build this recipe with python 2, so I simply deleted this condition

### CODE REVIEW

**Comment by jdblischak** [comment]
This PR confirms the same import error identified in #31 that only affects the linux-aarch64 builds:

```sh
import: 'tiledb.sql'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/libtiledb-sql-py_1733943837684/test_tmp/run_test.py", line 2, in <module>
    import tiledb.sql
  File "/home/conda/feedstock_root/build_artifacts/libtiledb-sql-py_1733943837684/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/tiledb/sql/__init__.py", line 22, in <module>
    from ._mysql import (
ImportError: libcrypt.so.1: cannot open shared object file: No such file or directory
```

**Comment by jdblischak** [comment]
Unclear what the problem is:

* I confirmed that libxcrypt is installed in the test conda env
* The import test used to pass on linux-aarch64, eg a few months ago in September in https://github.com/conda-forge/libtiledb-sql-py-feedstock/pull/30, and conda-forge hasn't uploaded new libxcrypt binaries in 11 months

https://github.com/conda-forge/libxcrypt-feedstock/commits/main/
https://anaconda.org/conda-forge/libxcrypt/files

**Comment by ihnorton** [comment]
This linkage must somehow be coming through from `mysql_config`, even though `-lcrypto` is explicitly removed in the build script: https://github.com/TileDB-Inc/TileDB-SQL-Py/blob/978525c53ab1054e54497329e2a2af93b851c653/setup_posix.py#L116-L121

**Comment by jdblischak** [comment]
Dropped the linux-aarch64 build. We are no longer building the upstream libtiledb-sql-feedstock for linux-aarch64

xref: https://github.com/conda-forge/libtiledb-sql-py-feedstock/pull/30#issuecomment-2539844244

**Pull request merged**
