### PR TITLE
add ```-Wno-error=implicit-function-declaration``` in Apple Silicon

### PR DESCRIPTION
**Pull request by DimitrisStaratzis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by DimitrisStaratzis** [comment]
@conda-forge-admin, please rerender

**Review by ihnorton — APPROVED** [review]
LGTM assuming it passes. Thanks!

**Comment by DimitrisStaratzis** [comment]
Made this a warning. To completely resolve we need to declare the function prototypes in the TIleDB-SQL-Py repo.

**Comment by DimitrisStaratzis** [comment]
Full CI passed. Merging with build number bump to publish artifacs

**Pull request merged**
