### PR TITLE
Migrate linux-aarch64 build from Travis to Azure

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

---

I noticed that the linux-aarch64 builds were being run on Travis. This PR updates these builds to run on Azure so that all the builds are in one place.

xref: #8

### CODE REVIEW

**Review by ihnorton — APPROVED** [review]
LGTM pending CI

**Comment by jdblischak** [comment]
Hmmm...fun. I've been having bad luck with PRs this week.

The osx-arm64 builds are all failing, but that has nothing to do with the changes proposed in this PR (the linux-aarch64 builds all passed on Azure).

The osx-arm64 builds [passed](https://github.com/conda-forge/libtiledb-sql-py-feedstock/commit/b9106faef1de032aa5700bd72d684481b5ae83d6) for commit b9106faef1de032aa5700bd72d684481b5ae83d6. What's changed? @DimitrisStaratzis I assume this the same error you are troubleshooting in to https://github.com/conda-forge/libtiledb-sql-py-feedstock/pull/22#issuecomment-1994777344

**Comment by DimitrisStaratzis** [comment]
> Hmmm...fun. I've been having bad luck with PRs this week.
> 
> The osx-arm64 builds are all failing, but that has nothing to do with the changes proposed in this PR (the linux-aarch64 builds all passed on Azure).
> 
> The osx-arm64 builds [passed](https://github.com/conda-forge/libtiledb-sql-py-feedstock/commit/b9106faef1de032aa5700bd72d684481b5ae83d6) for commit [b9106fa](https://github.com/conda-forge/libtiledb-sql-py-feedstock/commit/b9106faef1de032aa5700bd72d684481b5ae83d6). What's changed? @DimitrisStaratzis I assume this the same error you are troubleshooting in to [#22 (comment)](https://github.com/conda-forge/libtiledb-sql-py-feedstock/pull/22#issuecomment-1994777344)

Nothing has changed this is weird. #22 does not have to do with CI failures but rather a runtime issue we have in arm Macs

**Comment by jdblischak** [comment]
PR #24 demonstrates that the failing osx-arm64 builds are unrelated to the changes in this PR

**Review by DimitrisStaratzis — APPROVED** [review]

**Pull request merged**
